Add `extraPackages` to each hook and propagate them to `enabledPackages`
cachix/git-hooks.nix pull request #430
Opened 2024-04-12 16:57 UTC by 9999years

`enabledPackages` can be used to include all the relevant packages for enabled hooks into a developer environment. Unfortunately, it doesn't automatically pick up on packages other than a hook's default `package` attribute. By adding an `extraPackages` option to each hook, these other packages can be seamlessly added to developer environments.

I've included defaults for `extraPackages` for the following hooks:

- `treefmt`: the enabled `settings.formatters`
- `clippy`, `rustfmt`: the `packageOverrides`
- `dune-fmt`: the enabled `settings.extraRuntimeInputs`

2024-04-13 06:22 UTC, domenkozar commented
Shouldn't we just propagate `packageOverrides`?

2024-04-16 14:06 UTC, sandydoo commented
> E.g. couldn't someone create one set of packageOverrides and use it for all their hooks

We should remove `packageOverrides` from the base hook module. It was a mistake on my part to add it there. It doesn't do anything by default and the only 3 hooks that use it overload the option anyway. 

It's sole purpose is to provide an access point to override specific dependencies for hooks that have them. And the reason it's an attrset and not a list of packages (like `extraPackages`) is so that the package names show up in the docs.  I initially wanted to expose the wrapper packages for these hooks and let people use overrides, but I wasn't sure how to document this. So we compromised.

> I'm also not quite sure how that would work with e.g. treefmt -- I suppose treefmt could just implicitly use all the packageOverrides values as formatters, but it seems a little clumsy. What do you think?

Yeah, `treefmt` is not like the other hooks. That's why `treefmt.settings.formatters` exists.

@domenkozar, I quite like this actually. `packageOverrides` doesn't fit the bill because we have hooks like `treefmt` and `dune-fmt`. We can make probably mark it as `internal` though?

2024-04-16 14:17 UTC, sandydoo approved these changes
LGTM!

The only question I have is whether we might want to mark this as `internal`? But then it won't show up in the docs at all, which is annoying if you're writing a custom hook. 🤷 Probably good as it is.

2024-04-16 14:47 UTC, roberth commented
> `internal`?

I've argued for a category of "advanced" options, a middle ground, but that's controversial, in the context of NixOS at least.
- https://github.com/NixOS/nixpkgs/issues/257300

2024-04-16 17:43 UTC, 9999years commented
We could also replace `packageOverrides` with individual package options.

2024-04-17 10:06 UTC, sandydoo requested changes

2024-04-17 10:06 UTC, sandydoo commented on modules/hooks.nix
> +              config.settings.packageOverrides.rustfmt
```suggestion
              config.packageOverrides.cargo
              config.packageOverrides.rustfmt
```

2024-04-17 10:06 UTC, sandydoo commented on modules/hooks.nix
> +              config.settings.packageOverrides.clippy
```suggestion
              config.packageOverrides.cargo
              config.packageOverrides.clippy
```

2024-04-17 10:11 UTC, sandydoo commented
> We could also replace `packageOverrides` with individual package options.

That's what we're doing now, no? Or do you have something else in mind?

https://github.com/cachix/git-hooks.nix/blob/40e6053ecb65fcbf12863338a6dcefb3f55f1bf8/modules/hooks.nix#L176-L185

2024-04-17 15:43 UTC, 9999years commented
> That's what we're doing now, no? Or do you have something else in mind?

Oh, I see. I thought it was an arbitrary attrset of packages for some reason.

Maybe we should remove the `packageOverrides` level then, so that overriding packages can be done with `package` for the main package and (e.g.) `cargo` and `clippy` for the others (rather than packageOverrides.cargo`).

2024-04-19 16:06 UTC, sandydoo commented
> Maybe we should remove the packageOverrides level then, so that overriding packages can be done with package for the main package and (e.g.) cargo and clippy for the others (rather than packageOverrides.cargo`).

Maybe 🤷 The extra level excludes the (admittedly unlikely) possibility of naming conflicts with other pre-commit options.

2024-04-20 17:05 UTC, sandydoo approved these changes

2024-04-22 08:50 UTC, merged