feat: add typstyle
cachix/git-hooks.nix pull request #454
Opened 2024-06-06 21:17 UTC by leana8959

Hello,

I have added `typstyle`, a formatter for `typst`.

Though, there's a little issue: it's not in the version of nixpkgs pinned by this project, and it won't work. What would be a good solution ?

Thanks and have a nice day :)

2024-06-19 18:31 UTC, leana8959 commented
_Psst, The CI failed because `typstyle` is not in the `nixpkgs` pinned in the flake._

2024-06-19 18:35 UTC, sandydoo requested changes
I'll bump nixpkgs so that this works out of the box.

2024-06-19 18:35 UTC, sandydoo commented on nix/tools.nix
> +, typstyle
```suggestion
, typstyle ? null
```

2024-06-19 18:35 UTC, sandydoo commented on modules/hooks.nix
> +        entry = "${hooks.typstyle.package}/bin/typstyle";
You can check whether `tools.typstyle` is `null` and print a nicer error message if it is. Search for `lib.throwIf` for examples.

2024-06-19 19:14 UTC, leana8959 commented
The requested changes were added :)

2024-06-20 08:40 UTC, merged

2024-06-20 11:59 UTC, sandydoo commented
Thanks, @leana8959!