feat: add an option to `cabal2nix` hook for specifying output filename.
cachix/git-hooks.nix pull request #531
Opened 2024-12-09 11:33 UTC by rsrohitsingh682

At present after enabling `cabal2nix` hook, it generates a file named `default.nix` which is hardcoded. It is better if user has an option to specify the filename instead of using hardcoded `default.nix`.

This PR adds an option to `cabal2nix` hook to specify output filename generated by running `cabal2nix`.

2024-12-12 18:41 UTC, rsrohitsingh682 commented
@sandydoo @NorFairKing Any thoughts on this PR ?

2024-12-15 01:37 UTC, NorfairKing commented
I don't see a use case so think this needlessly complicating things but I also don't really care :shrug:

2024-12-15 20:35 UTC, rsrohitsingh682 commented
> I don't see a use case so think this needlessly complicating things but I also don't really care 🤷

It's required for me as I don't want pre-commit hook to generate a `default.nix`.  Anyways since the default is `default.nix` so the default behaviour still remains the same.

2024-12-19 03:50 UTC, rsrohitsingh682 commented
@sandydoo Could you please help with the review ?

2024-12-21 15:58 UTC, sandydoo requested changes
Otherwise, LGTM

2024-12-21 15:58 UTC, sandydoo commented on modules/hooks.nix
> +            output_filename =
Lets stick with camelCase for the settings, if possible.

2024-12-21 16:00 UTC, sandydoo commented
The CI failure is unrelated. This branch needs a rebase on master.

2024-12-21 16:12 UTC, sandydoo approved these changes

2024-12-21 16:13 UTC, merged